---

- name: Change ASM Policy Enforcement Mode
  hosts: bigip-ve.hk.ntnxlab.local
  connection: local

  vars:
    provider:
      server: "{{ ansible_host }}"
      #user: "{{ ansible_user }}"
      #password: "{{ ansible_password }}"
      validate_certs: no
      server_port: 443
  tasks:
     - name: Change ASM Policy to Blocking
       bigip_command:
               commands:
                       - modify asm policy WAF-POLICY blocking-mode enabled
                       - publish asm policy WAF-POLICY
               provider: "{{ provider }}"
